version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...

builds:
  - main: ./src/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: ["tar.gz"]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: ["zip"]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: hidedot
    directory: Formula
    repository:
      owner: youhide
      name: homebrew-youhide
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Youri T. K. K. Mattar
      email: youri@youhide.com.br
    homepage: "https://github.com/youhide/hideDot"
    description: "A dotfiles manager written in Go"
    license: "GPL-3.0"
    test: |
      system "#{bin}/hidedot --help"
    install: |
      bin.install "hideDot" => "hidedot"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
